configs:
  - name: payer_address
    value: '0x1fd0E4bcF1d77361dD285612D0F17cFac35da3eD'
  - name: min_diff_block_start
    value: 100
  - name: min_block_end
    value: 30000
  - name: min_block_reward
    value: 0.01
  - name: range_block_change
    value: 3
  - name: amount_payment
    value: 1000